// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCor2PhDYPJU8X6ZGiMUnbDFRBTaAkhyII',
    appId: '1:145558379243:web:fc7e18c2e1e6381772fcae',
    messagingSenderId: '145558379243',
    projectId: 'flutterfirebaseotp-69145',
    authDomain: 'flutterfirebaseotp-69145.firebaseapp.com',
    storageBucket: 'flutterfirebaseotp-69145.appspot.com',
    measurementId: 'G-Z65L6CK7E7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAatf_wKom9ycVr32AajKpgLDz-hR7zeGA',
    appId: '1:145558379243:android:fb64d6a827ed149272fcae',
    messagingSenderId: '145558379243',
    projectId: 'flutterfirebaseotp-69145',
    storageBucket: 'flutterfirebaseotp-69145.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDwPaBlBN7U7cYLAAaxYju3uLEkfkJkKs',
    appId: '1:145558379243:ios:3fd6bc473eceef2a72fcae',
    messagingSenderId: '145558379243',
    projectId: 'flutterfirebaseotp-69145',
    storageBucket: 'flutterfirebaseotp-69145.appspot.com',
    iosClientId: '145558379243-bveqs3g6etqtcn42h2u9s653br81rucl.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterfirebaseotp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDwPaBlBN7U7cYLAAaxYju3uLEkfkJkKs',
    appId: '1:145558379243:ios:1cff556fec30c25972fcae',
    messagingSenderId: '145558379243',
    projectId: 'flutterfirebaseotp-69145',
    storageBucket: 'flutterfirebaseotp-69145.appspot.com',
    iosClientId: '145558379243-8unq5fcc4qic5riuctmb5kbemv2aoba0.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterfirebaseotp.RunnerTests',
  );
}
